In [21]:
import pandas as pd
import numpy as np

In [22]:
data = pd.read_csv("Data Cleaning 12.08.csv")
df = pd.DataFrame(data)
df.head()

,name,planet_status,mass,mass_error_min,mass_error_max,mass_sini,mass_sini_error_min,mass_sini_error_max,radius,radius_error_min
0,109 Psc b,Confirmed,5.743,0.289,1.011,6.3830,0.078,0.078,1.152,NaN
1,112 Psc b,Confirmed,NaN,0.005,0.004,0.0330,0.005,0.004,NaN,NaN
2,112 Psc c,Confirmed,9.866,1.781,3.190,NaN,NaN,NaN,NaN,NaN
3,11 UMi b,Confirmed,NaN,1.100,1.100,11.0873,1.100,1.100,NaN,NaN
4,14 And Ab,Confirmed,NaN,0.230,0.230,4.6840,0.230,0.230,NaN,NaN

In [23]:
#rows and columns
df.shape

(5986, 10)

In [24]:
#null values
df.isnull().sum()

name                      0
planet_status             0
mass                   3907
mass_error_min         3169
mass_error_max         3169
mass_sini              4784
mass_sini_error_min    4947
mass_sini_error_max    4947
radius                 1418
radius_error_min       1893
dtype: int64

In [25]:
#duplicated values
df.duplicated().sum()

np.int64(0)

In [27]:
# Replace infinity values (inf) with NaN (null val)
df = df.replace([np.inf, -np.inf], np.nan)

# Fix any negative values in error columns by making them positive
error_cols = [col for col in df.columns if 'error' in col]
df[error_cols] = df[error_cols].abs()

In [28]:
#fix missing mass vals - combine mass and mass_sini
df['mass'] = df['mass'].fillna(df['mass_sini'])
df.head()

,name,planet_status,mass,mass_error_min,mass_error_max,mass_sini,mass_sini_error_min,mass_sini_error_max,radius,radius_error_min
0,109 Psc b,Confirmed,5.7430,0.289,1.011,6.3830,0.078,0.078,1.152,NaN
1,112 Psc b,Confirmed,0.0330,0.005,0.004,0.0330,0.005,0.004,NaN,NaN
2,112 Psc c,Confirmed,9.8660,1.781,3.190,NaN,NaN,NaN,NaN,NaN
3,11 UMi b,Confirmed,11.0873,1.100,1.100,11.0873,1.100,1.100,NaN,NaN
4,14 And Ab,Confirmed,4.6840,0.230,0.230,4.6840,0.230,0.230,NaN,NaN

In [29]:
df.isnull().sum()

name                      0
planet_status             0
mass                   2924
mass_error_min         3169
mass_error_max         3178
mass_sini              4784
mass_sini_error_min    4947
mass_sini_error_max    4947
radius                 1418
radius_error_min       1893
dtype: int64

In [30]:
#remove remaining missing 
df = df.dropna(subset=['mass'])
df.isnull().sum()

name                      0
planet_status             0
mass                      0
mass_error_min          245
mass_error_max          254
mass_sini              1860
mass_sini_error_min    2023
mass_sini_error_max    2023
radius                 1418
radius_error_min       1500
dtype: int64

In [31]:
# Fix missing errors by fixing the empty values with 0 (otherwise calculations might break)
error_cols = ['mass_error_min', 'mass_error_max', 'mass_sini_error_min', 'mass_sini_error_max', 'radius_error_min']
for col in error_cols:
    df[col] = df[col].fillna(0)

In [32]:
df.isnull().sum()

name                      0
planet_status             0
mass                      0
mass_error_min            0
mass_error_max            0
mass_sini              1860
mass_sini_error_min       0
mass_sini_error_max       0
radius                 1418
radius_error_min          0
dtype: int64

In [34]:
# missing radius
df['radius'] = df['radius'].fillna(df['radius'].median())
df.isnull().sum()

name                      0
planet_status             0
mass                      0
mass_error_min            0
mass_error_max            0
mass_sini              1860
mass_sini_error_min       0
mass_sini_error_max       0
radius                    0
radius_error_min          0
dtype: int64

In [35]:
# drop the redundant mass_sini column
df = df.drop(columns=['mass_sini'])
df.isnull().sum()

name                   0
planet_status          0
mass                   0
mass_error_min         0
mass_error_max         0
mass_sini_error_min    0
mass_sini_error_max    0
radius                 0
radius_error_min       0
dtype: int64

In [36]:
df.describe()

,mass,mass_error_min,mass_error_max,mass_sini_error_min,mass_sini_error_max,radius,radius_error_min
count,3062.000000,3062.000000,3062.000000,3062.000000,3062.000000,3062.000000,3062.000000
mean,1.653834,0.298412,0.633639,0.072848,0.081591,0.699602,0.037602
std,2.866224,1.299681,15.478593,0.384327,0.562223,0.400280,0.869896
min,0.000190,0.000000,0.000000,0.000000,0.000000,0.026000,0.000000
25%,0.033000,0.004112,0.003592,0.000000,0.000000,0.485730,0.000000
50%,0.450000,0.031950,0.030000,0.000000,0.000000,0.675350,0.002095
75%,1.858750,0.150000,0.140000,0.006217,0.006000,0.816000,0.023000
max,50.000000,53.500000,850.000000,13.000000,20.900000,6.900000,48.000000

In [38]:
# Drops non-numeric columns like name
df.corr(numeric_only=True)

,mass,mass_error_min,mass_error_max,mass_sini_error_min,mass_sini_error_max,radius,radius_error_min
mass,1.000000,0.355795,0.077871,0.248392,0.212409,0.184454,-0.005694
mass_error_min,0.355795,1.000000,0.052689,0.277648,0.203593,0.038371,-0.003247
mass_error_max,0.077871,0.052689,1.000000,0.020508,0.031372,0.002362,-0.001227
mass_sini_error_min,0.248392,0.277648,0.020508,1.000000,0.737325,0.000291,-0.007144
mass_sini_error_max,0.212409,0.203593,0.031372,0.737325,1.000000,-0.010665,-0.005292
radius,0.184454,0.038371,0.002362,0.000291,-0.010665,1.000000,0.062880
radius_error_min,-0.005694,-0.003247,-0.001227,-0.007144,-0.005292,0.062880,1.000000

In [39]:
df['planet_status'].value_counts()

planet_status
Confirmed    3062
Name: count, dtype: int64

In [40]:
# save final dataset
df.to_csv("Cleaned_Exoplanet_Data_Final.csv", index=False)
df.describe()

,mass,mass_error_min,mass_error_max,mass_sini_error_min,mass_sini_error_max,radius,radius_error_min
count,3062.000000,3062.000000,3062.000000,3062.000000,3062.000000,3062.000000,3062.000000
mean,1.653834,0.298412,0.633639,0.072848,0.081591,0.699602,0.037602
std,2.866224,1.299681,15.478593,0.384327,0.562223,0.400280,0.869896
min,0.000190,0.000000,0.000000,0.000000,0.000000,0.026000,0.000000
25%,0.033000,0.004112,0.003592,0.000000,0.000000,0.485730,0.000000
50%,0.450000,0.031950,0.030000,0.000000,0.000000,0.675350,0.002095
75%,1.858750,0.150000,0.140000,0.006217,0.006000,0.816000,0.023000
max,50.000000,53.500000,850.000000,13.000000,20.900000,6.900000,48.000000